import React from 'react';

interface PrivacyPolicyProps {
  onNavigateBack: () => void;
}

export const PrivacyPolicy: React.FC<PrivacyPolicyProps> = ({ onNavigateBack }) => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-900 to-gray-800 text-gray-300 p-4 sm:p-8 flex flex-col items-center">
      <div className="w-full max-w-3xl bg-gray-800 p-6 sm:p-8 rounded-xl shadow-2xl">
        <h1 className="text-3xl font-bold text-purple-400 mb-6 text-center">Privacy Policy</h1>

        <p className="mb-4">Your privacy is important to us. This Privacy Policy explains how Gemini GameGen handles your information.</p>

        <h2 className="text-xl font-semibold text-purple-300 mt-6 mb-3">Information We Collect</h2>
        <ul className="list-disc list-inside mb-4 pl-4 space-y-2">
          <li><strong>Prompts:</strong> The text prompts you enter to generate or revise games are sent to the Google Gemini API.</li>
          <li><strong>API Key:</strong> Your Google Gemini API Key, configured via the <code className="bg-gray-700 px-1 rounded text-sm">process.env.API_KEY</code> environment variable, is used to authenticate requests to the Google Gemini API. This application does not store it persistently beyond runtime memory needed for API calls.</li>
          <li><strong>Generated Code:</strong> The HTML, CSS, and JavaScript code generated by the AI.</li>
          <li><strong>Local Storage Data:</strong> If you use the "Save to History" feature or have unsaved work, the application stores this data (prompts, code, timestamps) in your browser's local storage. This data remains on your computer and is not transmitted to any external server by this application itself.</li>
        </ul>

        <h2 className="text-xl font-semibold text-purple-300 mt-6 mb-3">How We Use Information</h2>
        <ul className="list-disc list-inside mb-4 pl-4 space-y-2">
          <li><strong>To Provide the Service:</strong> Your prompts and API key are used to interact with the Google Gemini API to generate game code.</li>
          <li><strong>To Improve User Experience:</strong> Local storage is used to allow you to save your work and game history for your convenience.</li>
        </ul>

        <h2 className="text-xl font-semibold text-purple-300 mt-6 mb-3">Information Sharing</h2>
        <p className="mb-4">We do not share your personal information with third parties, except as necessary to provide the service:</p>
        <ul className="list-disc list-inside mb-4 pl-4 space-y-2">
          <li><strong>Google Gemini API:</strong> Your prompts and API key are sent to Google to process your requests. Your interactions with the Google Gemini API are subject to Google's Privacy Policy and Terms of Service.</li>
        </ul>
        <p className="mb-4">This application itself does not have a backend server and does not collect or store your data on any servers controlled by the application developer.</p>


        <h2 className="text-xl font-semibold text-purple-300 mt-6 mb-3">Data Storage and Security</h2>
        <p className="mb-4">Data stored in your browser's local storage (current work, game history) is as secure as your browser and computer system. We do not implement additional encryption for local storage data.</p>
        <p className="mb-4">You are responsible for the security of your API key. Ensure it is not exposed publicly.</p>

        <h2 className="text-xl font-semibold text-purple-300 mt-6 mb-3">Your Rights</h2>
        <p className="mb-4">You can clear data stored by this application in your browser's local storage by using your browser's built-in tools for managing website data or by using the "Reset Current State" and "Delete" (from history) functionalities within the app.</p>

        <h2 className="text-xl font-semibold text-purple-300 mt-6 mb-3">Third-Party Services</h2>
        <p className="mb-4">This application relies on the Google Gemini API. We encourage you to review Google's privacy policies.</p>
        
        <h2 className="text-xl font-semibold text-purple-300 mt-6 mb-3">Changes to This Policy</h2>
        <p className="mb-4">We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>

        <div className="mt-8 text-center">
          <button
            onClick={onNavigateBack}
            className="px-6 py-2.5 bg-purple-600 hover:bg-purple-700 text-white font-semibold rounded-lg shadow-md transition-all duration-150 ease-in-out focus:outline-none focus:ring-2 focus:ring-purple-500 focus:ring-offset-2 focus:ring-offset-gray-800"
          >
            Back to App
          </button>
        </div>
      </div>
      <footer className="w-full max-w-3xl mt-8 text-center text-sm text-gray-500">
        <p>&copy; {new Date().getFullYear()} Gemini GameGen</p>
      </footer>
    </div>
  );
};
