import React from 'react';

interface TermsOfServiceProps {
  onNavigateBack: () => void;
}

export const TermsOfService: React.FC<TermsOfServiceProps> = ({ onNavigateBack }) => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-900 to-gray-800 text-gray-300 p-4 sm:p-8 flex flex-col items-center">
      <div className="w-full max-w-3xl bg-gray-800 p-6 sm:p-8 rounded-xl shadow-2xl">
        <h1 className="text-3xl font-bold text-purple-400 mb-6 text-center">Terms of Service</h1>
        
        <p className="mb-4">Welcome to Gemini GameGen! These terms and conditions outline the rules and regulations for the use of Gemini GameGen's Website, located at this application.</p>
        <p className="mb-4">By accessing this website we assume you accept these terms and conditions. Do not continue to use Gemini GameGen if you do not agree to take all of the terms and conditions stated on this page.</p>

        <h2 className="text-xl font-semibold text-purple-300 mt-6 mb-3">API Key Usage</h2>
        <p className="mb-4">This application requires a Google Gemini API Key to function. This key is configured via an environment variable (<code className="bg-gray-700 px-1 rounded text-sm">process.env.API_KEY</code>) and is used solely to communicate with the Google Gemini API on your behalf to generate game code based on your prompts.</p>
        <p className="mb-4">You are responsible for securing your API key. The application does not store your API key beyond its operational runtime memory and sends it directly to Google's services. We are not responsible for any usage or charges incurred on your Google Gemini account.</p>

        <h2 className="text-xl font-semibold text-purple-300 mt-6 mb-3">Use of Generated Content</h2>
        <p className="mb-4">The game code (HTML, CSS, JavaScript) generated by the AI is provided "as is". While we strive for functional and creative outputs, we make no guarantees regarding its quality, functionality, security, or suitability for any purpose.</p>
        <p className="mb-4">You are free to use, modify, and distribute the generated code, subject to Google's terms for AI-generated content and any underlying open-source licenses if applicable (though this app primarily generates from scratch).</p>
        
        <h2 className="text-xl font-semibold text-purple-300 mt-6 mb-3">Local Storage</h2>
        <p className="mb-4">This application utilizes your browser's local storage to save your current work (HTML, CSS, JS) and your game history. This data is stored directly in your browser and is not transmitted to our servers.</p>

        <h2 className="text-xl font-semibold text-purple-300 mt-6 mb-3">User Conduct</h2>
        <p className="mb-4">You agree not to use the service to generate content that is illegal, harmful, offensive, or infringes on the rights of others.</p>

        <h2 className="text-xl font-semibold text-purple-300 mt-6 mb-3">Disclaimer</h2>
        <p className="mb-4">The service is provided "as is" without any warranties. We are not liable for any damages arising from your use of this application.</p>

        <h2 className="text-xl font-semibold text-purple-300 mt-6 mb-3">Changes to Terms</h2>
        <p className="mb-4">We reserve the right to revise these terms at any time. By using this website, you are expected to review these terms on a regular basis.</p>

        <div className="mt-8 text-center">
          <button
            onClick={onNavigateBack}
            className="px-6 py-2.5 bg-purple-600 hover:bg-purple-700 text-white font-semibold rounded-lg shadow-md transition-all duration-150 ease-in-out focus:outline-none focus:ring-2 focus:ring-purple-500 focus:ring-offset-2 focus:ring-offset-gray-800"
          >
            Back to App
          </button>
        </div>
      </div>
      <footer className="w-full max-w-3xl mt-8 text-center text-sm text-gray-500">
        <p>&copy; {new Date().getFullYear()} Gemini GameGen</p>
      </footer>
    </div>
  );
};
